### ISSUE TITLE
Feature: tag questions | Task: Question linking functionality

### ISSUE THREAD

**Issue by Quarks-1** [CMU-313/spring23-nodebb-team-up#10]
Assign ID link to questions such that the question can be referenced by users when posting 

**Estimated effort**: 10+ hrs

**Dependencies**: none

**Acceptance criteria**:

- Correct question is linked with @<number>
- Questions can be linked by anyone making/replying to a post
- Tests to verify that all questions have ID numbers

**Comment by Quarks-1** [comment]
The main reason this Issue was not completed by Sprint 1 was due to a lack of understanding of the codebase as well as the Nodebb test suite rejecting my changes.  Much of my time was spent trying to change the test cases to accept my initial changes, thus I wasn't able to work on anything past parsing data input and storing it.  We have restructured how we are approaching this feature for Sprint 2.

**Comment by HachiDD12** [comment]
Closed by PR #17
