### ISSUE TITLE
Feature: tag questions | Task: front-end display UI

### ISSUE THREAD

**Issue by Quarks-1** [CMU-313/spring23-nodebb-team-up#5]
Implement interactive front-end elements that displays question reference links

**Estimated effort**: 10+ hrs

**Dependencies**: Tag-questions back end implementation

**Acceptance criteria**:

- UI pop-up displayed when user types @ to show linked question
- User can confirm that they want to link specific question after it is found
- User can change question link by changing @ number
- Tests pass (correct output of tagging questions by using UI)

**Comment by amitag2** [comment]
We were unable to implement this feature within Sprint 1 as we initially planned because understanding how to make changes in NodeBB took longer than expected and we underestimated the effort needed for this feature.
