### ISSUE TITLE
Feature: bookmark questions | Task: front-end UI

### ISSUE THREAD

**Issue by ayla72** [CMU-313/spring23-nodebb-team-up#7]
Implement visual icon next to the corresponding question on the General Discussion page that demonstrates when a question has been bookmarked 

Estimated effort: 16-20 hrs

Dependencies:  back-end task for bookmark questions must be working 
    
Acceptance criteria:

- Fully interactive and functional.
- User actions (mark a question/discussion/post as bookmarked or un-bookmarked) work as intended - when user clicks bookmark 
       icon for unmarked question it becomes filled in and vice versa.
- Has no visible glitches - unmarked questions are never shown to be bookmarked and bookmarked questions are never shown to 
       be unmarked.
- Bookmarked questions visually differ from other post, users can differentiate been unmarked and marked questions.
- Test pass (correct output of adding and removing bookmarked posts with UI)

**Comment by amitag2** [comment]
I started working on this during Sprint 1 instead of the planned Sprint 2 because I was having difficulty understanding the code structure for the middleware and backend. 

Due to the back end not working, I still need to test how the implemented icon responds to a bookmarked post.
